
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shopapp?useSSL=false&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: huy22092003
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          form_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 871380307707-irun55qjvsmn9rju06rt1ncr7b6rp5bd.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:3000
            scope: email




  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



api:
  prefix: api/v1



jwt:
  expiration: 2592000 #30 days: 30 days * 24 hours * 60 min * 60 sec
  secretKey: 9oBo17NXniHYE+kVglvIxHDdRAanr6dh2SMB+Bsg2n0=


twilio:
  accountSid: AC4035f8058daec4653fa539fa0324fcfa
  authToken: ce549b13564728d8db5a9d196dc0bd65
  phoneNumber: +14242926164


